@url = https://springapplication-production.up.railway.app

###
GET {{url}}/tasks/getTasks

###
POST {{url}}/tasks/addTasks
Content-Type: application/json

  {
    "taskname": "sample task",
    "date": "sample date"
  }


###
GET https://springapplication-production.up.railway.app/tasks/getTasks

###
POST {{url}}/tasks/addTasks
Content-Type: application/json

{
  "taskname": "sample task",
  "date": "2024-01-27T15:47:53.4313895"
}

###

@date = sample date
@id1 = 2

GET {{url}}/{{id1}}/{{date}}